
package com.mindfire.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MathServiceService", targetNamespace = "http://service.mindfire.com", wsdlLocation = "http://localhost:8090/SampleJAX-WS-Project/services/MathService?wsdl")
public class MathServiceService
    extends Service
{

    private final static URL MATHSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException MATHSERVICESERVICE_EXCEPTION;
    private final static QName MATHSERVICESERVICE_QNAME = new QName("http://service.mindfire.com", "MathServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/SampleJAX-WS-Project/services/MathService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MATHSERVICESERVICE_WSDL_LOCATION = url;
        MATHSERVICESERVICE_EXCEPTION = e;
    }

    public MathServiceService() {
        super(__getWsdlLocation(), MATHSERVICESERVICE_QNAME);
    }

    public MathServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MATHSERVICESERVICE_QNAME, features);
    }

    public MathServiceService(URL wsdlLocation) {
        super(wsdlLocation, MATHSERVICESERVICE_QNAME);
    }

    public MathServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MATHSERVICESERVICE_QNAME, features);
    }

    public MathServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MathServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MathService
     */
    @WebEndpoint(name = "MathService")
    public MathService getMathService() {
        return super.getPort(new QName("http://service.mindfire.com", "MathService"), MathService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MathService
     */
    @WebEndpoint(name = "MathService")
    public MathService getMathService(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.mindfire.com", "MathService"), MathService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MATHSERVICESERVICE_EXCEPTION!= null) {
            throw MATHSERVICESERVICE_EXCEPTION;
        }
        return MATHSERVICESERVICE_WSDL_LOCATION;
    }

}
